config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy' 
  get     '/search',  to: 'movies#search',  as: :search
  resources :user_relationships,  only: [:create, :destroy]
  resources :favorite_folders,    except: [:index, :show]
  resources :favorite_movies,     only: [:create, :destroy] do
    patch :update_for, on: :collection
  end
  resources :movies do
    collection do
      get 'month', 'week', 'day', 'rank'
    end
  end
  resources :users do
    member do
      get :following, :followers, :favorites, :following_movies, :folder_edit
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @movies = Movie.limit(10)
    @popular_movies = Movie.joins(:playing).where("playings.created_at": (1.day.ago)..(Time.now)).group("playings.movie_id").reorder("count(playings.movie_id) desc").limit(10)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<div>
  <h2>最新の動画</h2>
  <% if @movies.any? %>
    <ol>
      <%= render @movies %>
    </ol>
  <% end %>
  <%= link_to "もっと見る", movies_path %>
</div>
<div>
  <% if @popular_movies.any? %>
    <h2>人気の動画</h2>
    <ol>
      <%= render @popular_movies %>
    </ol>
    <%= link_to "もっと見る", day_movies_path %>
  <% end %>
</div>