config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy' 
  get     '/search',  to: 'movies#search',  as: :search
  resources :user_relationships,  only: [:create, :destroy]
  resources :favorite_folders,    except: [:index, :show]
  resources :favorite_movies,     only: [:create, :destroy] do
    patch :update_for, on: :collection
  end
  resources :movies do
    collection do
      get 'month', 'week', 'day', 'rank'
    end
  end
  resources :users do
    member do
      get :following, :followers, :favorites, :following_movies, :folder_edit
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  
  has_many :movies
  has_many :active_relationships, class_name: "UserRelationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "UserRelationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships
  has_many :favorite_movies, dependent: :destroy
  has_many :favorites, through: :favorite_movies, source: :movie
  has_many :favorite_folders, dependent: :destroy
  
  # ハッシュ化パスワード認証機能を使用するための設定関数を実行
  has_secure_password
  
  validate :validate_name, on: :create
  validate :validate_password
  
  # 渡された文字列のハッシュ値を返す
  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  def self.new_token
    SecureRandom.urlsafe_base64
  end
  
  # ログイン情報記憶機能のためにDBにトークンを記録する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
    update_attribute(:authenticated_at, Time.now)
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(token)
    BCrypt::Password.new(remember_digest).is_password?(token) if remember_digest
  end
  
  # ログイン情報記憶機能のためのトークンを破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end
  
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
  
  # 引数で渡されたuserをフォローしていればtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  # 動画をお気に入りに追加する
  def add_to_favorites(movie)
    favorite_movies.create(movie_id: movie.id)
  end
  
  # 動画をお気に入りから削除する
  def remove_from_favorites(movie)
    favorite_movie = favorite_movies.find_by(movie_id: movie.id)
    return false unless favorite_movie
    favorite_movie.destroy
  end
  
  private
  
    def validate_name
      if name.blank?
        errors.add(:name, "入力する必要があります")
      elsif !((6..15) === name.length)
        errors.add(:name, "６から１５文字で入力してください")
      elsif !name.match(/\A[0-9a-zA-Z_]+\z/)
        errors.add(:name, "半角英数字,アンダースコアのみで入力してください")
      elsif User.exists?(name: name)
        errors.add(:name, "#{name}はすでに登録されています")
      end
    end
  
    def validate_password
      if password.blank?
        errors.add(:password, "入力する必要があります")
      elsif !((6..20) === password.length)
        errors.add(:password, "６から２０文字で入力してください")
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :logged_in_user,  only: [:index, :edit, :update, :destroy, :following, :followers, :favorites, :following_movies, :folder_edit]
  before_action :correct_user,    only: [:edit, :update, :following, :followers, :favorites, :following_movies, :folder_edit]
  before_action :admin_user,      only: [:index, :destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end
  
  def show
    @user = User.find(params[:id])
    @movies = @user.movies.paginate(page: params[:page])
    # todo 統合テストを生成して書く
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params.require(:user).permit(:name, :password, :password_confirmation))
    if @user.save
      log_in @user
      flash[:success] = "はじめまして#{@user.name}さん！"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.authenticate(params[:user][:old_password])
      if @user.update_attributes(user_params)
        flash[:success] = "パスワードを変更しました"
        redirect_to @user
      else
        render 'edit'
      end
    else
      @user.errors.add(:old_password, "今までのパスワードが正しくありません")
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_url
  end
  
  def following
    @title = "フォロー中のユーザー"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
  end
  
  def followers
    @title = "フォロワー"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render :following
  end
  
  # フォローしているユーザーのアップした動画
  def following_movies
    @user = User.find(params[:id])
    following_ids = "select followed_id from user_relationships where follower_id = #{@user.id}"
    @movies = Movie.where("user_id IN (#{following_ids})").paginate(page: params[:page])
  end
  
  # お気に入り動画リスト
  def favorites
    @movies = Movie.where(id: current_favorite_movie.select('movie_id')).paginate(page: params[:pate])
    @folders = @user.favorite_folders.all
    @movie = nil
  end
  
  # お気に入り動画をフォルダーに移動するフォームビューを描画
  def folder_edit
    @favorite_movies = current_favorite_movie.paginate(page: params[:page])
    @favorite_folder_array = unselected_favorite_folder
  end
  
  private
  
    def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  
    # リクエストされたページの正しいユーザーでなければホームにリダイレクトする
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
  
    # folder_idパラメータで指定されたフォルダ内のお気に入り動画を返す
    def current_favorite_movie
      @folder_id = params[:folder_id]
      FavoriteMovie.where(user_id: current_user, favorite_folder_id: @folder_id)
    end
  
    # ビューのselect下のoption用、カレントフォルダー以外のフォルダーの配列を返す
    def unselected_favorite_folder
      folders = []
      folders << ["フォルダーに分類しない", nil] if params[:folder_id]
      current_user.favorite_folders.where.not('favorite_folders.id': params[:folder_id]).each do |folder|
        folders << [folder.name, folder.id]
      end
      
      folders
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_movie_list.html.erb
<div>
  <% if @user.movies.any? %>
    <ol>
      <%= render @movies %>
    </ol>
    <%= will_paginate @movies %>
  <% end %>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "BAN!", user, method: :delete, data: { confirm: "#{user.name}を削除してよろしいですか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<%= provide(:title, 'パスワードの変更') %>
<h1>Users#edit@<%= @user.name %></h1>

<div>
  <%= form_for(@user) do |f| %>
    <%= render partial: 'shared/error_messages', locals: {obj: @user} %>
    
    <div>
    <%= f.label :password, "新しいパスワード" %>
    <%= f.password_field :password %>
    </div>
    
    <div>
    <%= f.label :password_confirmation, "再入力" %>
    <%= f.password_field :password_confirmation %>
    </div>
    
    <div>
    <%= f.label :old_password, "今までのパスワード" %>
    <%= f.password_field :old_password %>
    </div>
    
    <div>
    <%= f.submit "変更を保存する", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/users/favorites.html.erb
<% provide(:title, "お気に入り動画") %>
<h1>お気に入り動画</h1>
<%= render 'shared/user_stats' if current_user?(@user) %>
<div>
  <ul>
    <li><%= link_to "ユーザートップ", @user %></li>
    <li><%= link_to "フォローユーザーの動画", following_movies_user_path(@user) %></li>
  </ul>
  <h2><%= @movies.count %>個の動画</h2>
  <div><%= link_to "フォルダーを作成", new_favorite_folder_url %></div>
  <div><%= link_to("動画を他のフォルダーに移動", folder_edit_user_url(folder_id: @folder_id)) if @movies.any? %></div>
  <%= render partial: 'favorite_folders/folders', locals: {folders: @folders} if @folders.any? %>
  <%= render 'movie_list' %>
</div>

app/views/users/folder_edit.html.erb
<% provide(:title, "お気に入り動画を整理") %>
<h1>お気に入り動画を整理</h1>
<div>
  <h2><%= @favorite_movies.count %>個の動画</h2>
  <%= render partial: 'favorite_movies/move_to_folder', locals: {favorite_movies: @favorite_movies} if @favorite_movies.any? %>
</div>

app/views/users/following.html.erb
<% provide(:title, @title) %>
<h1><%= @user.name %></h1>
<%= render 'shared/user_stats' if current_user?(@user) %>
 <div>
  <ul>
    <li><%= link_to "ユーザートップ", @user %></li>
    <li><%= link_to "お気に入り動画", favorites_user_path(@user) %></li>
    <li><%= link_to "フォローユーザーの動画", following_movies_user_path(@user) %></li>
  </ul>
  <h2><%= @title %></h2>
  <% if @users.any? %>
    <ul>
      <%= render @users %>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/following_movies.html.erb
<% provide(:title, "フォローユーザーの動画") %>
<h1><%= @user.name %></h1>
<%= render 'shared/user_stats' if current_user?(@user) %>
<div>
  <ul>
    <li><%= link_to "ユーザートップ", @user %></li>
    <li><%= link_to "お気に入り動画", favorites_user_path(@user) %></li>
  </ul>
  <h2>フォローユーザーの動画： <%= @movies.count %></h2>
  <%= render 'movie_list' %>
</div>

app/views/users/index.html.erb
<% provide(:title, 'すべてのユーザー') %>
<h1>すべてのユーザー</h1>

<%= will_paginate %>

<ul>
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<%= provide(:title, 'Sign up') %>
<h1>Users#new</h1>

<div>
  <%= form_for(@user, url: signup_path) do |f| %>
    <%= render partial: 'shared/error_messages', locals: {obj: @user} %>
    
    <div>
    <%= f.label :name, "アカウント名" %>
    <%= f.text_field :name %>
    </div>
    
    <div>
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password %>
    </div>
    
    <div>
    <%= f.label :password_confirmation, "再入力" %>
    <%= f.password_field :password_confirmation %>
    </div>
    
    <div>
    <%= f.submit "この内容で登録する", class: "btn" %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1><%= @user.name %></h1>
<%= render 'follow_form' if logged_in? %>
<%= render 'shared/user_stats' if current_user?(@user) %>
<div>
  <ul>
    <li><%= link_to "お気に入り動画", favorites_user_path(@user) %></li>
    <li><%= link_to "フォローユーザーの動画", following_movies_user_path(@user) %></li>
  </ul>
  <h2>今までに追加した動画： <%= @user.movies.count %></h2>
  <%= render 'movie_list' %>
</div>