config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy' 
  get     '/search',  to: 'movies#search',  as: :search
  resources :user_relationships,  only: [:create, :destroy]
  resources :favorite_folders,    except: [:index, :show]
  resources :favorite_movies,     only: [:create, :destroy] do
    patch :update_for, on: :collection
  end
  resources :movies do
    collection do
      get 'month', 'week', 'day', 'rank'
    end
  end
  resources :users do
    member do
      get :following, :followers, :favorites, :following_movies, :folder_edit
    end
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  belongs_to :user
  belongs_to :linked_site
  has_many :favorite_movie, dependent: :destroy
  has_many :playing, dependent: :destroy
  
  default_scope -> { order(created_at: :desc) }
  
  validates :user_id, presence: true
  validate :validate_title
  validate :validate_url
  validate :validate_thumbnail
  validate :validate_tags
  
  def self.search(word)
    Movie.where(["tags like ? or title like ?", "%#{word}%", "%#{word}%"]) if word.present?
  end
  
  private
  
    def validate_title
      if title.blank?
        errors.add(:title, "入力する必要があります")
      elsif title.length > 40
        errors.add(:title, "４０文字以内で入力してください")
      end
    end
  
    def validate_url
      if url.blank?
        errors.add(:url, "入力する必要があります")
      end
    end

    def validate_thumbnail
      if thumbnail.blank?
        errors.add(:thumbnail, "入力する必要があります")
      end
    end

    def validate_tags
      if !tags.match(/\A,([^\s　,]+,)+\z/)
        errors.add(:tags, "タグの形式が正しくありません")
      end
    end
end

app/controllers/favorite_movies_controller.rb
class FavoriteMoviesController < ApplicationController
  
  before_action :logged_in_user
  before_action :correct_user, only: [:destroy]
  
  def create
    @movie = Movie.find(params[:movie_id])
    current_user.add_to_favorites(@movie)
    
    respond_to do |format|
      format.html { redirect_to request.referrer || root_url }
      format.js
    end
  end
  
  def destroy
    @movie = Movie.find(params[:movie_id])
    current_user.remove_from_favorites(@movie)
    
    respond_to do |format|
      format.html { redirect_to request.referrer || root_url }
      format.js
    end
  end
  
  def update_for
    folder = FavoriteFolder.find(params[:folder_id])
    params[:favorite_movie_ids].each do |id|
      move_to_folder(folder, FavoriteMovie.find(id))
    end
    redirect_to request.referer || favorites_user_url(current_user)
  end
  
  private
    
    # お気に入り動画をフォルダーに移動。動画かフォルダーがカレントユーザーのものでなければfalseを返す
    def move_to_folder(folder, favorite_movie)
      return unless current_user?(folder.user) && current_user?(favorite_movie.user)
      favorite_movie.update(favorite_folder_id: folder.id)
    end
  
    def correct_user
      @favorite_movie = current_user.favorite_movies.find_by(movie_id: params[:movie_id])
      redirect_to root_url unless @favorite_movie
    end
end

app/helpers/favorite_movies_helper.rb
module FavoriteMoviesHelper
end

app/views/favorite_movies/_move_to_folder.html.erb
<%= form_tag update_for_favorite_movies_url, method: :patch do %>
  <%= hidden_field_tag 'favorite_movie[]' %>
  
  <%= select_tag :folder_id , options_for_select(@favorite_folder_array) %>
  
  <% if favorite_movies.any? %>
    <ol>
    <% favorite_movies.each do |favorite_movie| %>
      <li>
        <%= label_tag "favorite_movie_#{favorite_movie.id}", favorite_movie.movie.title %> <%= check_box_tag 'favorite_movie_ids[]', favorite_movie.id, checked = false, id: "favorite_movie_#{favorite_movie.id}" %>
      </li>
    <% end %>
    </ol>
    <%= submit_tag "フォルダに移動" %>
    <div><%= link_to "戻る", favorites_user_url(current_user, folder_id: @folder_id) %></div>
    <%= will_paginate favorite_movies %>
  <% end %>
<% end %>

app/views/favorite_movies/create.js.erb
$("#favorite_form<%= @movie.id %>").html("<%= escape_javascript(render('movies/remove_favorite')) %>");

app/views/favorite_movies/destroy.js.erb
$("#favorite_form<%= @movie.id %>").html("<%= escape_javascript(render('movies/add_favorite')) %>");