config/routes.rb
Rails.application.routes.draw do

  root    'static_pages#home'
  get     '/signup',  to: 'users#new'
  post    '/signup',  to: 'users#create'
  get     '/login',   to: 'sessions#new'
  post    '/login',   to: 'sessions#create'
  delete  '/logout',  to: 'sessions#destroy' 
  get     '/search',  to: 'movies#search',  as: :search
  resources :user_relationships,  only: [:create, :destroy]
  resources :favorite_folders,    except: [:index, :show]
  resources :favorite_movies,     only: [:create, :destroy] do
    patch :update_for, on: :collection
  end
  resources :movies do
    collection do
      get 'month', 'week', 'day', 'rank'
    end
  end
  resources :users do
    member do
      get :following, :followers, :favorites, :following_movies, :folder_edit
    end
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <ul class="nav">
    <li>tag1</li>
    <li>tag2</li>
    <li>tag3</li>
  </ul>
  <p class="copyright">Adult Link Site</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to "Adult Link Site", root_path, class: "logo" %>
  <ul class="nav">
    <% if logged_in? %>
      <li><%= link_to "アカウント", current_user %></li>
      <li><%= link_to "パスワードの変更", edit_user_path(current_user) %></li>
      <li><%= link_to "ログアウト", logout_path, method: "delete" %></li>
    <% else %>
      <li><%= link_to "新規登録（無料）", signup_path %></li>
      <li><%= link_to "ログイン", login_path %></li>
    <% end %>
  </ul>
  <%= form_tag search_path, method: :get do %>
    <div>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "検索する", name: nil %>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="base">
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert _<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>